// Builds ../levels.js — the level ladder and the daily bank.
//   node games/c-queens/scripts/gen.js            # full rebuild (~15 min, mostly the Tricky 10×10s)
//   node games/c-queens/scripts/gen.js --quick    # smoke run: 6 ladder + 3 daily boards
// Boards are deterministic per slot (seeded by slot name), so re-running only
// changes a board if its spec or the engine changed.
const fs = require('fs');
const path = require('path');
const E = require('./engine-from-page.js');
const OUT = path.join(__dirname, '..', 'levels.js');
const quick = process.argv.includes('--quick');

// Ladder: 5×5 up to 10×10, eight boards per size, a long tail of 8–10, then
// 11×11 and 12×12 with one or two queens pre-placed to keep them tractable.
// Style: "islands" (small regions in one big sea) for most boards, "balanced"
// (evenly sized regions) for the Tricky ones and a sprinkling of the rest.
const ladder = [];
for (let N = 5; N <= 10; N++) {
  const tiers = N <= 6 ? [2, 2, 2, 2, 2, 3, 2, 3] : [2, 2, 2, 2, 3, 2, 2, 3];
  tiers.forEach((t, i) => ladder.push({ N, t, style: t === 3 || i % 3 === 1 ? 'balanced' : 'islands' }));
}
for (let i = 0; i < 52; i++) {
  const N = 8 + (i % 3);
  ladder.push({ N, t: i % 4 === 3 ? 3 : 2, style: i % 4 === 3 || i % 5 === 2 ? 'balanced' : 'islands' });
}
for (let i = 0; i < 8; i++) ladder.push({ N: 11, t: i % 4 === 3 ? 3 : 2, style: i % 3 === 1 ? 'balanced' : 'islands', givens: 1 });
for (let i = 0; i < 8; i++) ladder.push({ N: 12, t: i % 4 === 3 ? 3 : 2, style: i % 3 === 1 ? 'balanced' : 'islands', givens: 2 });
// Daily bank: 8–10, Steady/Tricky, indexed by day number.
const daily = [];
for (let i = 0; i < 120; i++) daily.push({ N: 8 + (i % 3), t: i % 3 === 2 ? 3 : 2, style: i % 3 === 2 || i % 4 === 1 ? 'balanced' : 'islands' });

const specs = quick ? { ladder: ladder.slice(0, 5).concat(ladder.slice(-2)), daily: daily.slice(0, 3) } : { ladder, daily };
const bank = { ladder: [], daily: [] };
const encode = (p) => {
  const e = { N: p.N, t: p.tier, s: p.solution, r: p.reg.map((row) => row.map((g) => g.toString(36)).join('')).join('') };
  if (p.given && p.given.length) e.g = p.given;
  return e;
};
const header = '// Generated by scripts/gen.js — do not edit by hand.\nwindow.CNQ_LEVELS = ';
const T0 = Date.now();
for (const key of ['ladder', 'daily']) {
  specs[key].forEach((sp, i) => {
    const t = Date.now();
    const p = E.generate(sp.N, sp.t, E.hashSeed(`cnq-${key}-${i}-${sp.N}-${sp.t}-${sp.style}`), 60, sp.style, sp.givens || 0);
    if (!p) throw new Error(`no puzzle for ${key} ${i}`);
    bank[key].push(encode(p));
    console.log(`${key} ${i + 1}/${specs[key].length} N=${sp.N} ${sp.style}${sp.givens ? ' +' + sp.givens : ''} want ${sp.t} got ${p.tier} ${Date.now() - t}ms (${((Date.now() - T0) / 1000).toFixed(0)}s)`);
    fs.writeFileSync(OUT + '.tmp', header + JSON.stringify(bank) + ';\n');   // progress checkpoint
  });
}
fs.renameSync(OUT + '.tmp', OUT);
console.log('wrote', OUT, bank.ladder.length, 'ladder +', bank.daily.length, 'daily');
